const SPANISH_BAD_WORDS = [
  'mierda',
  'caca',
  'puta',
  'puto',
  'putas',
  'putos',
  'pendejo',
  'pendeja',
  'pendejos',
  'pendejas',
  'carajo',
  'coño',
  'coños',
  'culo',
  'culos',
  'cabrón',
  'cabrona',
  'cabrones',
  'cabronas',
  'hijueputa',
  'hijueputas',
  'hijo de puta',
  'hija de puta',
  'malparido',
  'malparida',
  'malparidos',
  'malparidas',
  'gonorrea',
  'marica',
  'maricas',
  'maricón',
  'maricona',
  'maricones',
  'verga',
  'vergajo',
  'chingar',
  'chingada',
  'chingado',
  'chingadera',
  'joder',
  'jodido',
  'jodida',
  'jodidos',
  'jodidas',
  'jodiendo',
  'cojones',
  'cojón',
  'cojonudo',
  'gilipollas',
  'capullo',
  'capulla',
  'zorra',
  'zorro',
  'zorras',
  'zorros',
  'perra',
  'perras',
  'bastardo',
  'bastarda',
  'bastardos',
  'bastardas',
  'concha',
  'conchas',
  'conchudo',
  'conchuda',
  'conchatumadre',
  'conchetumare',
  'sorete',
  'pelotudo',
  'pelotuda',
  'pelotudos',
  'pelotudas',
  'boludo',
  'boluda',
  'boludos',
  'boludas',
  'weón',
  'weona',
  'weones',
  'weonas',
  'huevón',
  'huevona',
  'huevones',
  'huevonas',
  'huevada',
  'huevadas',
  'wea',
  'weas',
  'chucha',
  'chuchada',
  'chupapollas',
  'pajero',
  'pajera',
  'pajeros',
  'pajeras',
  'mamon',
  'mamona',
  'cabro',
  'imbecil',
  'imbécil',
  'estupido',
  'estúpido',
  'estupida',
  'estúpida',
  'putamadre',
  'puta madre',
  'tonto',
  'tarado',
  'tarada',
  'menso',
  'mensos',
  'mensada',
  'pendejada',
  'pendejadas',
]

export function containsBadWords(text: string): { hasBadWords: boolean; found: string[] } {
  const normalized = text.toLowerCase().trim()
  const found = SPANISH_BAD_WORDS.filter((badWord) => {
    const regex = new RegExp(`\\b${badWord.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i')
    return regex.test(normalized)
  })
  return { hasBadWords: found.length > 0, found }
}

export function filterBadWords(words: string[]): { clean: string[]; rejected: string[] } {
  const clean: string[] = []
  const rejected: string[] = []
  for (const word of words) {
    const { hasBadWords } = containsBadWords(word)
    if (hasBadWords) {
      rejected.push(word)
    } else {
      clean.push(word)
    }
  }
  return { clean, rejected }
}
